//This file is an autogenerated file, do not edit
#ifndef _HAL_FREQ_SELECTOR_H
#define _HAL_FREQ_SELECTOR_H
#if defined(CRYSTAL_12MHz) && defined(HAL_4MHz)
  // Master clock settings
  // Resulting freq 4.000 MHz (0.000 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 1
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_3
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 8
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_12MHz) && defined(HAL_8MHz)
  // Master clock settings
  // Resulting freq 8.000 MHz (0.000 ppm error)
  #define PLLA_DIV 3
  #define PLLA_MUL 16
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_8
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 8
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_12MHz) && defined(HAL_12MHz)
  // Master clock settings
  // Resulting freq 12.000 MHz (0.000 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 1
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 8
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_12MHz) && defined(HAL_64MHz)
  // Master clock settings
  // Resulting freq 64.000 MHz (0.000 ppm error)
  #define PLLA_DIV 3
  #define PLLA_MUL 16
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK
  #define ACTIVE_FWS 3
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 8
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_16MHz) && defined(HAL_4MHz)
  // Master clock settings
  // Resulting freq 4.000 MHz (0.000 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 1
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_4
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 6
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_16MHz) && defined(HAL_8MHz)
  // Master clock settings
  // Resulting freq 8.000 MHz (0.000 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 1
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_2
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 6
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_16MHz) && defined(HAL_12MHz)
  // Master clock settings
  // Resulting freq 12.000 MHz (0.000 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 6
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_8
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 6
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_16MHz) && defined(HAL_64MHz)
  // Master clock settings
  // Resulting freq 64.000 MHz (0.000 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 4
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK
  #define ACTIVE_FWS 3
  // USB (48MHz) clock settings
  // Resulting freq 48.000 MHz (0.000 ppm error)
  #define PLLB_DIV 1
  #define PLLB_MUL 6
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_18d432MHz) && defined(HAL_4MHz)
  // Master clock settings
  // Resulting freq 4.032 MHz (-7936.508 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 7
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_32
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 47.923 MHz (1602.564 ppm error)
  #define PLLB_DIV 5
  #define PLLB_MUL 26
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_18d432MHz) && defined(HAL_8MHz)
  // Master clock settings
  // Resulting freq 8.064 MHz (-7936.508 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 7
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK6
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 47.923 MHz (1602.564 ppm error)
  #define PLLB_DIV 5
  #define PLLB_MUL 26
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_18d432MHz) && defined(HAL_12MHz)
  // Master clock settings
  // Resulting freq 11.981 MHz (1602.564 ppm error)
  #define PLLA_DIV 5
  #define PLLA_MUL 26
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_8
  #define ACTIVE_FWS 0
  // USB (48MHz) clock settings
  // Resulting freq 47.923 MHz (1602.564 ppm error)
  #define PLLB_DIV 5
  #define PLLB_MUL 26
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(CRYSTAL_18d432MHz) && defined(HAL_64MHz)
  // Master clock settings
  // Resulting freq 64.512 MHz (-7936.508 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 7
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK_2
  #define ACTIVE_FWS 3
  // USB (48MHz) clock settings
  // Resulting freq 47.923 MHz (1602.564 ppm error)
  #define PLLB_DIV 5
  #define PLLB_MUL 26
  #define PLLB_DIV2 0
  #define USB_DIV 2
#elif defined(RC_INTERNAL) && defined(HAL_4MHz)
  // Master clock settings
  #define PLLA_DIV 1
  #define PLLA_MUL 1
  #define PLLA_DIV2 1
  #define MCK_DIV PMC_MCKR_PRES_CLK
  #define ACTIVE_FWS 0
  #define RC_FREQ RC_FREQ_4MHZ
#elif defined(RC_INTERNAL) && defined(HAL_8MHz)
  // Master clock settings
  #define PLLA_DIV 1
  #define PLLA_MUL 1
  #define PLLA_DIV2 1
  #define MCK_DIV PMC_MCKR_PRES_CLK
  #define ACTIVE_FWS 0
  #define RC_FREQ RC_FREQ_8MHZ
#elif defined(RC_INTERNAL) && defined(HAL_12MHz)
  // Master clock settings
  #define PLLA_DIV 1
  #define PLLA_MUL 1
  #define PLLA_DIV2 1
  #define MCK_DIV PMC_MCKR_PRES_CLK
  #define ACTIVE_FWS 0
  #define RC_FREQ RC_FREQ_12MHZ
#elif defined(RC_INTERNAL) && defined(HAL_64MHz)
  // Master clock settings
  // Resulting freq 64.000 MHz (0.000 ppm error)
  #define PLLA_DIV 1
  #define PLLA_MUL 16
  #define PLLA_DIV2 0
  #define MCK_DIV PMC_MCKR_PRES_CLK
  #define ACTIVE_FWS 3
  #define RC_FREQ RC_FREQ_4MHZ
#else
  #error "Unknown frequency configuration"
#endif
#endif
